import { f as fileDesc, m as messageDesc } from '../../file-8Ag42MRZ.js';

// Copyright 2021-2024 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/**
 * Describes the file google/protobuf/struct.proto.
 */
const file_google_protobuf_struct = /*@__PURE__*/fileDesc("Chxnb29nbGUvcHJvdG9idWYvc3RydWN0LnByb3RvEg9nb29nbGUucHJvdG9idWYihAEKBlN0cnVjdBIzCgZmaWVsZHMYASADKAsyIy5nb29nbGUucHJvdG9idWYuU3RydWN0LkZpZWxkc0VudHJ5GkUKC0ZpZWxkc0VudHJ5EgsKA2tleRgBIAEoCRIlCgV2YWx1ZRgCIAEoCzIWLmdvb2dsZS5wcm90b2J1Zi5WYWx1ZToCOAEi6gEKBVZhbHVlEjAKCm51bGxfdmFsdWUYASABKA4yGi5nb29nbGUucHJvdG9idWYuTnVsbFZhbHVlSAASFgoMbnVtYmVyX3ZhbHVlGAIgASgBSAASFgoMc3RyaW5nX3ZhbHVlGAMgASgJSAASFAoKYm9vbF92YWx1ZRgEIAEoCEgAEi8KDHN0cnVjdF92YWx1ZRgFIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3RIABIwCgpsaXN0X3ZhbHVlGAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLkxpc3RWYWx1ZUgAQgYKBGtpbmQiMwoJTGlzdFZhbHVlEiYKBnZhbHVlcxgBIAMoCzIWLmdvb2dsZS5wcm90b2J1Zi5WYWx1ZSobCglOdWxsVmFsdWUSDgoKTlVMTF9WQUxVRRAAQn8KE2NvbS5nb29nbGUucHJvdG9idWZCC1N0cnVjdFByb3RvUAFaL2dvb2dsZS5nb2xhbmcub3JnL3Byb3RvYnVmL3R5cGVzL2tub3duL3N0cnVjdHBi+AEBogIDR1BCqgIeR29vZ2xlLlByb3RvYnVmLldlbGxLbm93blR5cGVzYgZwcm90bzM");
/**
 * `NullValue` is a singleton enumeration to represent the null value for the
 * `Value` type union.
 *
 * The JSON representation for `NullValue` is JSON `null`.
 *
 * @generated from enum google.protobuf.NullValue
 */
var NullValue;
(function (NullValue) {
  /**
   * Null value.
   *
   * @generated from enum value: NULL_VALUE = 0;
   */
  NullValue[NullValue["NULL_VALUE"] = 0] = "NULL_VALUE";
})(NullValue || (NullValue = {}));

// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file rpc/proto/v1/auth.proto (package rpc.proto.v1, syntax proto3)
/* eslint-disable */
/**
 * Describes the file rpc/proto/v1/auth.proto.
 */
const file_rpc_proto_v1_auth = /*@__PURE__*/fileDesc("ChdycGMvcHJvdG8vdjEvYXV0aC5wcm90bxIMcnBjLnByb3RvLnYxIlQKE0F1dGhlbnRpY2F0ZVJlcXVlc3QSDQoFdG9rZW4YASABKAkSLgoNb3B0aW9uYWxfZGF0YRgKIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QidAoUQXV0aGVudGljYXRlUmVzcG9uc2USDAoEdXVpZBgBIAEoCRIOCgZhcHBfaWQYAiABKAkSDgoGaXNzdWVyGAMgASgJEi4KDW9wdGlvbmFsX2RhdGEYCiABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0Qj1aO2dpdGh1Yi5jb20vYXhpZWluZmluaXR5L3gtc2VydmljZS9nZW4vZ28vcnBjL3Byb3RvL3YxO3JwY3YxYgZwcm90bzM", [file_google_protobuf_struct]);
/**
 * Describes the message rpc.proto.v1.AuthenticateRequest.
 * Use `create(AuthenticateRequestSchema)` to create a new message.
 */
const AuthenticateRequestSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_auth, 0);
/**
 * Describes the message rpc.proto.v1.AuthenticateResponse.
 * Use `create(AuthenticateResponseSchema)` to create a new message.
 */
const AuthenticateResponseSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_auth, 1);

export { AuthenticateRequestSchema, AuthenticateResponseSchema, file_rpc_proto_v1_auth };
