import { f as fileDesc, m as messageDesc } from '../../file-8Ag42MRZ.js';
import { e as enumDesc } from '../../enum-DxRJVtGK.js';

// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file rpc/proto/v1/backup.proto (package rpc.proto.v1, syntax proto3)
/* eslint-disable */
/**
 * Describes the file rpc/proto/v1/backup.proto.
 */
const file_rpc_proto_v1_backup = /*@__PURE__*/fileDesc("ChlycGMvcHJvdG8vdjEvYmFja3VwLnByb3RvEgxycGMucHJvdG8udjEiRwoNQmFja3VwUmVxdWVzdBImCgR0eXBlGAEgASgOMhgucnBjLnByb3RvLnYxLkJhY2t1cFR5cGUSDgoGcGFyYW1zGAIgASgMIkgKDkJhY2t1cFJlc3BvbnNlEiYKBHR5cGUYASABKA4yGC5ycGMucHJvdG8udjEuQmFja3VwVHlwZRIOCgZyZXN1bHQYAiABKAwicAoNQ2hhbGxlbmdlSW5mbxIMCgR1dWlkGAEgASgJEhgKEGNoYWxsZW5nZV9zdHJpbmcYAiABKAkSEgoKY3JlYXRlZF9hdBgDIAEoAxIMCgRraW5kGAQgASgJEhUKDXRhcmdldF9vYmplY3QYBSABKAwiQAoSQ3JlYXRlQmFja3VwUGFyYW1zEhUKDWVuY3J5cHRlZF9rZXkYASABKAkSEwoLc2lnbl9yZXN1bHQYAiABKAkqXAoKQmFja3VwVHlwZRIbChdCQUNLVVBfVFlQRV9VTlNQRUNJRklFRBAAEhkKFUJBQ0tVUF9UWVBFX0NIQUxMRU5HRRABEhYKEkJBQ0tVUF9UWVBFX0NSRUFURRACQj1aO2dpdGh1Yi5jb20vYXhpZWluZmluaXR5L3gtc2VydmljZS9nZW4vZ28vcnBjL3Byb3RvL3YxO3JwY3YxYgZwcm90bzM");
/**
 * Describes the message rpc.proto.v1.BackupRequest.
 * Use `create(BackupRequestSchema)` to create a new message.
 */
const BackupRequestSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_backup, 0);
/**
 * Describes the message rpc.proto.v1.BackupResponse.
 * Use `create(BackupResponseSchema)` to create a new message.
 */
const BackupResponseSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_backup, 1);
/**
 * Describes the message rpc.proto.v1.ChallengeInfo.
 * Use `create(ChallengeInfoSchema)` to create a new message.
 */
const ChallengeInfoSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_backup, 2);
/**
 * Describes the message rpc.proto.v1.CreateBackupParams.
 * Use `create(CreateBackupParamsSchema)` to create a new message.
 */
const CreateBackupParamsSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_backup, 3);
/**
 * @generated from enum rpc.proto.v1.BackupType
 */
var BackupType;
(function (BackupType) {
  /**
   * @generated from enum value: BACKUP_TYPE_UNSPECIFIED = 0;
   */
  BackupType[BackupType["UNSPECIFIED"] = 0] = "UNSPECIFIED";
  /**
   * @generated from enum value: BACKUP_TYPE_CHALLENGE = 1;
   */
  BackupType[BackupType["CHALLENGE"] = 1] = "CHALLENGE";
  /**
   * @generated from enum value: BACKUP_TYPE_CREATE = 2;
   */
  BackupType[BackupType["CREATE"] = 2] = "CREATE";
})(BackupType || (BackupType = {}));
/**
 * Describes the enum rpc.proto.v1.BackupType.
 */
const BackupTypeSchema = /*@__PURE__*/enumDesc(file_rpc_proto_v1_backup, 0);

export { BackupRequestSchema, BackupResponseSchema, BackupType, BackupTypeSchema, ChallengeInfoSchema, CreateBackupParamsSchema, file_rpc_proto_v1_backup };
