import { f as fileDesc, m as messageDesc } from '../../file-8Ag42MRZ.js';
import { e as enumDesc } from '../../enum-DxRJVtGK.js';

// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file rpc/proto/v1/message.proto (package rpc.proto.v1, syntax proto3)
/* eslint-disable */
/**
 * Describes the file rpc/proto/v1/message.proto.
 */
const file_rpc_proto_v1_message = /*@__PURE__*/fileDesc("ChpycGMvcHJvdG8vdjEvbWVzc2FnZS5wcm90bxIMcnBjLnByb3RvLnYxIkAKB01lc3NhZ2USJwoEdHlwZRgBIAEoDjIZLnJwYy5wcm90by52MS5NZXNzYWdlVHlwZRIMCgRkYXRhGAIgASgMKq0BCgtNZXNzYWdlVHlwZRIdChlQQVlFUl9NRVNTQUdFX1VOU1BFQ0lGSUVEEAASIAocUEFZRVJfTUVTU0FHRV9HRU5FUkFURV9OT05DRRABEh4KGlBBWUVSX01FU1NBR0VfQUNDRVNTX1RPS0VOEAISIQodUEFZRVJfTUVTU0FHRV9QQVlFUl9TSUdOQVRVUkUQChIaChZTRU5EX01FU1NBR0VfU0lHTl9IQVNIEGRCPVo7Z2l0aHViLmNvbS9heGllaW5maW5pdHkveC1zZXJ2aWNlL2dlbi9nby9ycGMvcHJvdG8vdjE7cnBjdjFiBnByb3RvMw");
/**
 * Describes the message rpc.proto.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
const MessageSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_message, 0);
/**
 * @generated from enum rpc.proto.v1.MessageType
 */
var MessageType;
(function (MessageType) {
  /**
   * @generated from enum value: PAYER_MESSAGE_UNSPECIFIED = 0;
   */
  MessageType[MessageType["PAYER_MESSAGE_UNSPECIFIED"] = 0] = "PAYER_MESSAGE_UNSPECIFIED";
  /**
   * @generated from enum value: PAYER_MESSAGE_GENERATE_NONCE = 1;
   */
  MessageType[MessageType["PAYER_MESSAGE_GENERATE_NONCE"] = 1] = "PAYER_MESSAGE_GENERATE_NONCE";
  /**
   * @generated from enum value: PAYER_MESSAGE_ACCESS_TOKEN = 2;
   */
  MessageType[MessageType["PAYER_MESSAGE_ACCESS_TOKEN"] = 2] = "PAYER_MESSAGE_ACCESS_TOKEN";
  /**
   * @generated from enum value: PAYER_MESSAGE_PAYER_SIGNATURE = 10;
   */
  MessageType[MessageType["PAYER_MESSAGE_PAYER_SIGNATURE"] = 10] = "PAYER_MESSAGE_PAYER_SIGNATURE";
  /**
   * @generated from enum value: SEND_MESSAGE_SIGN_HASH = 100;
   */
  MessageType[MessageType["SEND_MESSAGE_SIGN_HASH"] = 100] = "SEND_MESSAGE_SIGN_HASH";
})(MessageType || (MessageType = {}));
/**
 * Describes the enum rpc.proto.v1.MessageType.
 */
const MessageTypeSchema = /*@__PURE__*/enumDesc(file_rpc_proto_v1_message, 0);

export { MessageSchema, MessageType, MessageTypeSchema, file_rpc_proto_v1_message };
