import { f as fileDesc, m as messageDesc } from '../../file-8Ag42MRZ.js';

// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file rpc/proto/v1/payer.proto (package rpc.proto.v1, syntax proto3)
/* eslint-disable */
/**
 * Describes the file rpc/proto/v1/payer.proto.
 */
const file_rpc_proto_v1_payer = /*@__PURE__*/fileDesc("ChhycGMvcHJvdG8vdjEvcGF5ZXIucHJvdG8SDHJwYy5wcm90by52MSIuChZQYXllckFjY2Vzc1Rva2VuUGFyYW1zEhQKDHNpd2VfbWVzc2FnZRgBIAEoCSItChRQYXllckFjY2Vzc1Rva2VuRGF0YRIVCg1hY2NjZXNzX3Rva2VuGAEgASgJQj1aO2dpdGh1Yi5jb20vYXhpZWluZmluaXR5L3gtc2VydmljZS9nZW4vZ28vcnBjL3Byb3RvL3YxO3JwY3YxYgZwcm90bzM");
/**
 * Describes the message rpc.proto.v1.PayerAccessTokenParams.
 * Use `create(PayerAccessTokenParamsSchema)` to create a new message.
 */
const PayerAccessTokenParamsSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_payer, 0);
/**
 * Describes the message rpc.proto.v1.PayerAccessTokenData.
 * Use `create(PayerAccessTokenDataSchema)` to create a new message.
 */
const PayerAccessTokenDataSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_payer, 1);

export { PayerAccessTokenDataSchema, PayerAccessTokenParamsSchema, file_rpc_proto_v1_payer };
