import { f as fileDesc, m as messageDesc } from '../../file-8Ag42MRZ.js';
import { e as enumDesc } from '../../enum-DxRJVtGK.js';

// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file rpc/proto/v1/rpc.proto (package rpc.proto.v1, syntax proto3)
/* eslint-disable */
/**
 * Describes the file rpc/proto/v1/rpc.proto.
 */
const file_rpc_proto_v1_rpc = /*@__PURE__*/fileDesc("ChZycGMvcHJvdG8vdjEvcnBjLnByb3RvEgxycGMucHJvdG8udjEiQwoFRnJhbWUSIAoEdHlwZRgBIAEoDjISLnJwYy5wcm90by52MS5UeXBlEgoKAmlkGAIgASgFEgwKBGRhdGEYAyABKAwiJgoFRXJyb3ISDAoEY29kZRgBIAEoBBIPCgdtZXNzYWdlGAIgASgJIhUKAk9rEg8KB21lc3NhZ2UYAiABKAkiHQoHU2Vzc2lvbhISCgpzZXNzaW9uX2lkGAEgASgJKkoKBFR5cGUSFAoQVFlQRV9VTlNQRUNJRklFRBAAEg0KCVRZUEVfREFUQRABEg4KClRZUEVfRVJST1IQAhINCglUWVBFX0RPTkUQA0I9WjtnaXRodWIuY29tL2F4aWVpbmZpbml0eS94LXNlcnZpY2UvZ2VuL2dvL3JwYy9wcm90by92MTtycGN2MWIGcHJvdG8z");
/**
 * Describes the message rpc.proto.v1.Frame.
 * Use `create(FrameSchema)` to create a new message.
 */
const FrameSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_rpc, 0);
/**
 * Describes the message rpc.proto.v1.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
const ErrorSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_rpc, 1);
/**
 * Describes the message rpc.proto.v1.Ok.
 * Use `create(OkSchema)` to create a new message.
 */
const OkSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_rpc, 2);
/**
 * Describes the message rpc.proto.v1.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
const SessionSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_rpc, 3);
/**
 * @generated from enum rpc.proto.v1.Type
 */
var Type;
(function (Type) {
  /**
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  Type[Type["UNSPECIFIED"] = 0] = "UNSPECIFIED";
  /**
   * @generated from enum value: TYPE_DATA = 1;
   */
  Type[Type["DATA"] = 1] = "DATA";
  /**
   * @generated from enum value: TYPE_ERROR = 2;
   */
  Type[Type["ERROR"] = 2] = "ERROR";
  /**
   * @generated from enum value: TYPE_DONE = 3;
   */
  Type[Type["DONE"] = 3] = "DONE";
})(Type || (Type = {}));
/**
 * Describes the enum rpc.proto.v1.Type.
 */
const TypeSchema = /*@__PURE__*/enumDesc(file_rpc_proto_v1_rpc, 0);

export { ErrorSchema, FrameSchema, OkSchema, SessionSchema, Type, TypeSchema, file_rpc_proto_v1_rpc };
