import { f as fileDesc, m as messageDesc } from '../../file-8Ag42MRZ.js';
import { e as enumDesc } from '../../enum-DxRJVtGK.js';

// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file rpc/proto/v1/sign.proto (package rpc.proto.v1, syntax proto3)
/* eslint-disable */
/**
 * Describes the file rpc/proto/v1/sign.proto.
 */
const file_rpc_proto_v1_sign = /*@__PURE__*/fileDesc("ChdycGMvcHJvdG8vdjEvc2lnbi5wcm90bxIMcnBjLnByb3RvLnYxIkMKC1NpZ25SZXF1ZXN0EiQKBHR5cGUYASABKA4yFi5ycGMucHJvdG8udjEuU2lnblR5cGUSDgoGcGFyYW1zGAIgASgMIh4KDFNpZ25SZXNwb25zZRIOCgZyZXN1bHQYASABKAwiKgoXU2VuZFRyYW5zYWN0aW9uUmVzcG9uc2USDwoHdHhfaGFzaBgBIAEoCSpXCghTaWduVHlwZRIZChVTSUdOX1RZUEVfVU5TUEVDSUZJRUQQABIVChFTSUdOX1RZUEVfTUVTU0FHRRABEhkKFVNJR05fVFlQRV9UUkFOU0FDVElPThACQj1aO2dpdGh1Yi5jb20vYXhpZWluZmluaXR5L3gtc2VydmljZS9nZW4vZ28vcnBjL3Byb3RvL3YxO3JwY3YxYgZwcm90bzM");
/**
 * Describes the message rpc.proto.v1.SignRequest.
 * Use `create(SignRequestSchema)` to create a new message.
 */
const SignRequestSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_sign, 0);
/**
 * Describes the message rpc.proto.v1.SignResponse.
 * Use `create(SignResponseSchema)` to create a new message.
 */
const SignResponseSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_sign, 1);
/**
 * Describes the message rpc.proto.v1.SendTransactionResponse.
 * Use `create(SendTransactionResponseSchema)` to create a new message.
 */
const SendTransactionResponseSchema = /*@__PURE__*/messageDesc(file_rpc_proto_v1_sign, 2);
/**
 * @generated from enum rpc.proto.v1.SignType
 */
var SignType;
(function (SignType) {
  /**
   * @generated from enum value: SIGN_TYPE_UNSPECIFIED = 0;
   */
  SignType[SignType["UNSPECIFIED"] = 0] = "UNSPECIFIED";
  /**
   * @generated from enum value: SIGN_TYPE_MESSAGE = 1;
   */
  SignType[SignType["MESSAGE"] = 1] = "MESSAGE";
  /**
   * @generated from enum value: SIGN_TYPE_TRANSACTION = 2;
   */
  SignType[SignType["TRANSACTION"] = 2] = "TRANSACTION";
})(SignType || (SignType = {}));
/**
 * Describes the enum rpc.proto.v1.SignType.
 */
const SignTypeSchema = /*@__PURE__*/enumDesc(file_rpc_proto_v1_sign, 0);

export { SendTransactionResponseSchema, SignRequestSchema, SignResponseSchema, SignType, SignTypeSchema, file_rpc_proto_v1_sign };
