window.APP_CONFIG = {
	limits: {
		defaultMaxRowsPerTable: 15,
		defaultFontSize: 13,
		minFontSize: 8,
		maxFontSize: 24,
		minRowsPerTable: 1,
		maxRowsPerTable: 100,
	},
	print: {
		downloadFileName: "MaSieuThi.html",
		paperSize: "A4",
		documentTitle: "Mã siêu thị",
	},
	labels: {
		appTitle: "Công cụ tạo HTML in mã siêu thị",
		eyebrow: "Ứng dụng web",
		mainTitle: "Công cụ tạo HTML in mã siêu thị",
		subtitle: "Tải tệp Excel, cấu hình bố cục in và xuất HTML ngay trong trình duyệt.",
		excelFileLabel: "Chọn tệp Excel (.xlsx)",
		orientationLabel: "Chiều giấy",
		maxRowsLabel: "Số hàng mỗi bảng",
		fontSizeLabel: "Cỡ chữ (px)",
		buttonGenerate: "Tạo xem trước",
		buttonPrint: "In trực tiếp",
		buttonDownload: "Tải tệp HTML",
		previewTitle: "Xem trước",
		previewFrameTitle: "Khung xem trước bản in",
		optionLandscape: "Ngang",
		optionPortrait: "Dọc",
		defaultStatus: "Chưa tải tệp.",
		emptyPreview: "Không có dữ liệu",
		previewMetaPattern: "{{mode}} | {{orientation}} | {{rows}} hàng | {{fontSize}}px",
		orientationPortrait: "dọc",
		orientationLandscape: "ngang",
		modeFourTables: "4 bảng/trang",
		modeTwoTables: "2 bảng/trang",
		statsStoreCount: "Mã siêu thị",
		statsItemCount: "Dòng sản phẩm",
		statsMaxRows: "Dòng lớn nhất/mã",
	},
	messages: {
		fileNotSelected: "Chưa chọn tệp.",
		readingExcel: "Đang đọc tệp Excel...",
		invalidData: "Không tìm thấy dữ liệu hợp lệ trong 3 cột đầu tiên.",
		loadSuccess: "Đã tải xong: {{count}} mã siêu thị.",
		readFileError: "Đọc tệp lỗi: {{error}}",
		needExcelData: "Cần tải dữ liệu Excel trước.",
		maxRowsOutOfRange: "Số hàng mỗi bảng phải trong khoảng {{min}} - {{max}}.",
		fontSizeOutOfRange: "Cỡ chữ phải trong khoảng {{min}} - {{max}}px.",
		previewReady: "Đã tạo xem trước. Bạn có thể bấm In trực tiếp hoặc tải tệp HTML.",
		printWithoutPreview: "Hãy tạo xem trước trước khi in.",
		printWindowError: "Không mở được khung xem trước để in.",
		printDialogOpened: "Đã mở hộp thoại in của trình duyệt.",
		downloadWithoutPreview: "Hãy tạo xem trước trước khi tải tệp.",
		downloadSuccess: "Đã tải xong tệp HTML.",
	},
	table: {
		headers: ["Mã siêu thị", "Tên sản phẩm", "Số lượng"],
		continuationSuffix: "(tiếp)",
		pageNumberPattern: "Trang {{page}}/{{total}}",
	},
};
